### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt4'

### ISSUE THREAD

**Issue by xsqian** [udacity/CarND-Camera-Calibration#1]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-c9afb263aacf> in <module>()
      4 import matplotlib.image as mpimg
      5 import glob
----> 6 get_ipython().magic('matplotlib qt')
      7 
      8 fname = 'calibration_test.png'

/Users/xqian/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

/Users/xqian/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

<decorator-gen-104> in matplotlib(self, line)

/Users/xqian/anaconda/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/Users/xqian/anaconda/lib/python3.6/site-packages/IPython/core/magics/pylab.py in matplotlib(self, line)
     98             print("Available matplotlib backends: %s" % backends_list)
     99         else:
--> 100             gui, backend = self.shell.enable_matplotlib(args.gui)
    101             self._show_matplotlib_backend(args.gui, backend)
    102 

/Users/xqian/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   2947                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   2948 
-> 2949         pt.activate_matplotlib(backend)
   2950         pt.configure_inline_support(self, backend)
   2951 

/Users/xqian/anaconda/lib/python3.6/site-packages/IPython/core/pylabtools.py in activate_matplotlib(backend)
    306 
    307     import matplotlib.pyplot
--> 308     matplotlib.pyplot.switch_backend(backend)
    309 
    310     # This must be imported last in the matplotlib series, after

/Users/xqian/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    231     matplotlib.use(newbackend, warn=False, force=True)
    232     from matplotlib.backends import pylab_setup
--> 233     _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    234 
    235 

/Users/xqian/anaconda/lib/python3.6/site-packages/matplotlib/backends/__init__.py in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/Users/xqian/anaconda/lib/python3.6/site-packages/matplotlib/backends/backend_qt4agg.py in <module>()
     16 
     17 
---> 18 from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
     19 
     20 from .backend_agg import FigureCanvasAgg

/Users/xqian/anaconda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py in <module>()
     14 
     15 from .backend_agg import FigureCanvasAgg
---> 16 from .backend_qt5 import QtCore
     17 from .backend_qt5 import QtGui
     18 from .backend_qt5 import FigureManagerQT

/Users/xqian/anaconda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py in <module>()
     24 
     25 from matplotlib.widgets import SubplotTool
---> 26 import matplotlib.backends.qt_editor.figureoptions as figureoptions
     27 
     28 from .qt_compat import (QtCore, QtGui, QtWidgets, _getSaveFileName,

/Users/xqian/anaconda/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py in <module>()
     18 import matplotlib
     19 from matplotlib import cm, markers, colors as mcolors
---> 20 import matplotlib.backends.qt_editor.formlayout as formlayout
     21 from matplotlib.backends.qt_compat import QtGui
     22 

/Users/xqian/anaconda/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py in <module>()
     54 
     55 from matplotlib import colors as mcolors
---> 56 from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
     57 
     58 

/Users/xqian/anaconda/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py in <module>()
    139     # have been changed in the above if block
    140     if QT_API in [QT_API_PYQT, QT_API_PYQTv2]:  # PyQt4 API
--> 141         from PyQt4 import QtCore, QtGui
    142 
    143         try:

ModuleNotFoundError: No module named 'PyQt4'

**Comment by mvirgo** [comment]
Just run `pip install pyqt4` or use the [anaconda environment](https://github.com/udacity/CarND-Term1-Starter-Kit) for Term 1 - Anaconda installs this by default.
