### ISSUE TITLE
Notebook crashing with docker image

### ISSUE THREAD

**Issue by SmokeShine** [udacity/CarND-Camera-Calibration#3]
OS
Ubuntu 18.04.2 LTS

Docker Image:
docker pull udacity/carnd-term1-starter-kit

Docker Run:
docker run -it --rm --entrypoint "/run.sh" -p 8888:8888 -v ~/Documents/Github/Self\ Driving\ Car\ Engineer/CarND-Camera-Calibration/:/src udacity/carnd-term1-starter-kit

Error Lines:
%matplotlib qt

Error:
Kernel Died

**Comment by UAnjali** [comment]
Though we are a little late to respond, we are closing out the issue because it has already been addressed in [this](https://github.com/udacity/CarND-Camera-Calibration/issues/2) issue.
Thank you.
